config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('news/', include('sportsnews.urls')),
    path('live-scores/', include('live_scores.urls')),
    path('', include('pages.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('about/', views.about_view, name='about'),
    path("contact/", views.contact_view, name="contact")
]

users/urls.py
# users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'users'

urlpatterns = [
    path("login/", views.UserLogin.as_view(), name="login"),
    path("signup/", views.UserSignup.as_view(), name="signup"),
    path("logout/", LogoutView.as_view(template_name='users/logged_out.html'), name="logout"),
]

users/forms.py
from django import forms
from django.contrib.auth.models import User

class SignupForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "username", "password"]

users/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.views.generic import CreateView
from django.contrib.auth.models import User
from .forms import SignupForm
# Create your views here.
class UserLogin(LoginView):
    template_name = "users/login.html"


class UserSignup(CreateView):
    model = User
    form_class = SignupForm
    template_name = "users/signup.html"
    success_url = "/users/login"

    def form_valid(self, form):
        user = form.save(commit=False)
        pass_text = form.cleaned_data["password"]
        user.set_password(pass_text)
        user.save()

        return super().form_valid(form)

templates/users/logged_out.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Logged Out{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/logout.css' %}">
{% endblock %}

{% block content %}
<div class="logout‑wrapper">
  <div class="logout‑card">
    <h2>You are Logged Out</h2>
    <p>Thanks for visiting. Feel free to log in again.</p>
    <a href="{% url 'users:login' %}" class="btn btn‑primary">Log In Again</a>
  </div>
</div>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
<div class="login-wrapper">
  <div class="login-card">
    <h2>Welcome Back</h2>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn-primary">Log In</button>
    </form>
    <p class="signup-link">Don’t have an account? <a href="{% url 'users:signup' %}">Sign up</a></p>
  </div>
</div>
{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Sign Up{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
<div class="login-wrapper">
  <div class="login-card">
    <h2>Create an Account</h2>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn-primary">Sign Up</button>
    </form>
    <p class="signup-link">Already have an account? <a href="{% url 'users:login' %}">Log in</a></p>
  </div>
</div>
{% endblock %}